name: Build and Test
on:
  push:
    branches:
      - PA3
jobs:
  gradle_build_test:
    name: Gradle build and test
    strategy:
      matrix:
        os: [ ubuntu-latest,macos-latest,windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
          check-latest: true
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
